apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: challenge-metafar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jotitadev/challenge-metafar-k8s'
    targetRevision: HEAD
    path: 'despliegue'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metafar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true