apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: challenge-metafar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jotitadev/challenge-metafar-k8s'
    targetRevision: HEAD
    path: 'despliegue'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metafar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: challenge-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL2pvdGl0YWRldi9jaGFsbGVuZ2UtbWV0YWZhci1rOHM=  # Base64 encoded repo URL (https://github.com/jotitadev/challenge-metafar-k8s)
type: Opaque